Auto Start Server: false
Binsize: 500.0
Data Directory: ./results/data_magentarsurroundings
Dip Threshold: 0.7
DipFlare Directory: ./results/dipflare_magentarsurroundings
Enable Output: true
Flare Threshold: 0.7
Log Directory: ./results/logs_magentarsurroundings
Minimum AvgCountPerSec: 0.01
Minimum Counts: 10
Object Name: 01:00:43.0 -72:11:33
Object is Position: true
Output Directory: ./results/output_magentarsurroundings
Search Radius (arcmin): 3
Significance Threshold: 3.0
